name: Publish

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - run: npm i -g pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install and build
        run: pnpm install

      - run: pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
