name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version accepted by `npm version *`'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - run: npm i -g pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install and build
        run: pnpm ci

      - run: pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$GITHUB_REF_NAME" # GITHUB_REF_NAME is the tag name in `on.push.tags` workflows
